# Generated by Django 2.0.4 on 2018-05-01 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_auto_20180426_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='_photo_albums_+', to='imager_images.Album'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imager_images.Photo'),
        ),
        migrations.AlterField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='_album_photos_+', to='imager_images.Photo'),
        ),
    ]
